### Site Settings ###
title               : Prarthana Krishnamurthy
description         : >-
                      I turn coffee :coffee: into code,
                      use tabs over spaces
                      and never broke production.
baseurl             : "/pkrishna.github.io"            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : pkrishna1801/pkrishna.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md



### Author Info ###
author:
  name              : Prarthana Krishnamurthy
  image             : https://media.licdn.com/dms/image/v2/D5635AQEpqtmcqzc-nQ/profile-framedphoto-shrink_400_400/profile-framedphoto-shrink_400_400/0/1707458325681?e=1746331200&v=beta&t=TMmRzacR7kDLPKZ_InVJU5EUYjw6S-uqEjHjfN-Y4pY
  behance           : Prarthana Krishnamurthy
# dribbble          : your_username
  email             : krishnamurthy.p@northeastern.edu
  # facebook          : your_username
  github            : https://github.com/pkrishna1801
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : https://www.linkedin.com/in/prarthana181k/
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name




### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
